name: Docker Build Proxies-Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

    build:
      name: proxies-action
      runs-on: linux-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKER_USER}}
            password: ${{secrets.DOCKER_PASS1}}
            
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: mract1on/proxies-action:latest
